### ISSUE TITLE
Alien Abduction Borb

### ISSUE THREAD

**Issue by dance2die** [rionmonster/borbs#17]
Context: 

     We are now facing alien threats.
     **Borb** was no exception.

Can we have a borb being abducted by a UFO? Kind of like how [this cow](https://www.google.com/search?q=alien+cow&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj61IP-xfXUAhWI2D4KHUfkDaQQ_AUICigB&biw=1157&bih=691#imgrc=3ZPqjRsR6_HG_M:) is getting abducted?

**Comment by rionmonster** [comment]
Added necessary borb for abduction; Including custom abduction image in this thread.

**Comment by rionmonster** [comment]
![image](https://user-images.githubusercontent.com/1325081/28028178-4c479982-6561-11e7-8403-7b0d0f9483ce.png)

**Comment by dance2die** [comment]
Thank you , Rion!

**Comment by rionmonster** [comment]
👍
