### ISSUE TITLE
Borb Eagle

### ISSUE THREAD

**Issue by swyxio** [rionmonster/borbs#22]
Like a bald eagle but borb

**Comment by swyxio** [comment]
majestic.

**Comment by swyxio** [comment]
erm.. american flag without stars? too hard? or just unpatriotic?

**Comment by LemmingRyan** [comment]
Closed for un-patriotism...

**Comment by rionmonster** [comment]
> erm.. american flag without stars? too hard? or just unpatriotic? 

![image](https://user-images.githubusercontent.com/1325081/28086573-13ff004e-6645-11e7-8373-26b38b03d467.png)

**Comment by swyxio** [comment]
Now that is the image of Freedom. and Borbdom.
